baseURL: "https://adorable-biscuit-3b82eb.netlify.app"
title: R. A. Lukmanov
paginate: 20
theme: PaperMod

defaultContentLanguage: en
languages:
  ru:
    #languagedirection: rtl
    title: –†—É—Å—Ç–∞–º –õ—É–∫–º–∞–Ω–æ–≤
    weight: 2
  en:
    params:
      linkedin: https://linkedin.com/whoever
    title: Rustam A. Lukmanov
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true #Swithces on JS scritps and tags


enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rustam A. Lukmanov
  description: "Personal website"
  keywords: [Blog, Portfolio, PaperMod]
  paginate: 100
  #author: Lukmanov R.A.
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  ##Search paprams
  params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/circle3.png"
    favicon16x16: "/circle3.png"
    favicon32x32: "/circle3.png"
    apple_touch_icon: "/circle3.png"
    safari_pinned_tab: "/circle3.png"

  label:
    text: "| R.A. Lukmanov "
    icon: /circle.png
    iconHeight: 35

  # profile-mode
 # profileMode:
    enabled: true # needs to be explicitly set
    title: Hi \U0001f44b there!
    #subtitle: "This is subtitle"
    subtitle: "
    


> ### Hi \U0001f44b I am a Research Scientist. I am interested in scalable, principled methods for analyzing graph data in an unsupervised manner. &nbsp;  


I received Ph.D. \U0001f393 in experimental phyiscs at the University of Bern, advised by Prof. Peter Wurz. I did my masters and bachelors at Saint Petersburg State University in Saint Petersburg, Russia. My M.Sc. advisor was Alexey Goncharov. In Russian, my name reads as –†—É—Å—Ç–∞–º –õ—É–∫–º–∞–Ω–æ–≤.

For publications, see Google Scholar. For code, see GitHub.

Feel free to contact me by email: mail at rustam-lukmanov dot ru.


> Right now I am working on "
    #imageUrl: "/box.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: my image
    buttons:
      - name: Blog
        url: blog
      - name: Publications
        url: publications
      - name: Resume
        url: cv
      - name: Contact Information
        url: contact
  # home-info mode
  homeInfoParams:
    Title: " [Rustam A. Lukmanov üë®üèª‚Äçüî¨](/cv/)"
    Content: "
    <p> I am a Research Scientist interested in scalable, unsupervised methods for construction and analysis of graph data. Much of my focus lies in the intersection of analytical chemsitry and graph-theoretic data processing. Currently, dabbling in the world of entrepreneurship
    </p>
    <br/>
    <p>   


    </p>  

  
  
      I received a Ph.D. \U0001f393 in experimental phyiscs at the [<u>University of Bern</u>](https://www.unibe.ch/index_eng.html), advised by [<u>Prof. Peter Wurz</u>](https://www.space.unibe.ch/about_us/personen/prof_dr_wurz_peter/index_eng.html) and [<u>Dr. Maker Tulej</u>](http://www.marek-tulej.ch/). 
        
      The A. in my name stands for my patronym and it reads as Abubakirovich (–ê–±—É–±–∞–∫–∏—Ä–æ–≤–∏—á).
        
        Considerable part of my research is about creating graph-structured objects from chemical/sensor data and efficient mining of the structural organization of such objects. More broadly my reaserch devoted to bridging the hardware and software development for **efficient** and **fast** insight retrieval from analytical setups.  I did my masters and bachelors at Saint Petersburg State University in Saint Petersburg, Russia.  
   <p>
   <br/>
   </p>   
               

      For publications, see [**Google Scholar**](https://scholar.google.ch/citations?user=uJXEpcgAAAAJ&hl=en&oi=ao) or my [**LOOP**](https://loop.frontiersin.org/people/1234341/overview) profile. For code, see GitHub.

      Feel free to contact me through links attached below.

      
      > - [**Curriculum Vitae** üëî](/cv/)  
        
      > - [**Publications** üìù](/publications/)  

      > - [**Contact me** üìß](/contact/)
  
        
      
      You can also follow me on social media:
        
      > - [**Instagram** üìß](https://www.instagram.com/lukmanovr/)/[**Twitter** üóÉÔ∏è](/archives/) / [**LinkedIn** üìù](/publications/) / [**Telegram** üëî](/cv/)
        

      Sometimes, I write here about random things, check it out below:  
      
      > - [**Archive** üóÉÔ∏è](/archives/)"
  #socialIcons:
  #  - name: twitter
  #    url: "https://twitter.com/"
  #  - name: stackoverflow
  #    url: "https://stackoverflow.com"
  #  - name: github
  #    url: "https://github.com/"
  #  - name: google scholar
  #    url: "https://scholar.google.ch/citations?user=uJXEpcgAAAAJ&hl=en&oi=ao/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Publications
      name: Publications
      url: /publications/
      weight: 30
    - identifier: CV
      name: CV
      url: /CV/
      weight: 40
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: Search
      name: Search
      url: /search/
      weight: 60