baseURL: "https://adorable-biscuit-3b82eb.netlify.app"
title: R. A. Lukmanov
paginate: 20
theme: PaperMod

defaultContentLanguage: en
languages:
  ru:
    params:
    #languagedirection: rtl
    title: –†—É—Å—Ç–∞–º –õ—É–∫–º–∞–Ω–æ–≤
    weight: 1
    menu:
      main:
          - identifier: –ë–ª–æ–≥
            name: –ë–ª–æ–≥
            url: /blog/
            weight: 10
          - identifier: –¢–µ–≥–∏
            name: –¢–µ–≥–∏
            url: /tags/
            weight: 20
          - identifier: –ü—É–±–ª–∏–∫–∞—Ü–∏–∏
            name: –ü—É–±–ª–∏–∫–∞—Ü–∏–∏
            url: /publications/
            weight: 30
          - identifier: CV
            name: CV
            url: /CV/
            weight: 40
          - identifier: –°–≤—è–∑–∞—Ç—å—Å—è
            name: –°–≤—è–∑–∞—Ç—å—Å—è
            url: /contact/
            weight: 50
          - identifier: –ü–æ–∏—Å–∫
            name: –ü–æ–∏—Å–∫
            url: /search/
            weight: 60
    profileMode:
     enabled: false
     subtitle: –í—Å–µ–º –ø—Ä–∏–≤–µ—Ç
     imageUrl: "Profile.jpg"
    homeInfoParams:
        Title: "–õ—É–∫–º–∞–Ω–æ–≤ –†—É—Å—Ç–∞–º –ê–±—É–±–∞–∫–∏—Ä–æ–≤–∏—á üë®üèª‚Äçüî¨"
        Content: "
        <img src='/images/circle_ru.png' alt='Girl in a jacket' width='400' 
                                align='middle'>
                                <br>
        –Ø –Ω–∞—É—á–Ω—ã–π —Å–æ—Ç—Ä—É–¥–Ω–∏–∫, –∑–∞–∏–Ω—Ç–µ—Ä–µ—Å–æ–≤–∞–Ω–Ω—ã–π –≤ –º–∞—Å—à—Ç–∞–±–∏—Ä—É–µ–º—ã—Ö, –Ω–µ–∫–æ–Ω—Ç—Ä–æ–ª–∏—Ä—É–µ–º—ã—Ö –º–µ—Ç–æ–¥–∞—Ö –ø–æ—Å—Ç—Ä–æ–µ–Ω–∏—è –∏ –∞–Ω–∞–ª–∏–∑–∞ –≥—Ä–∞—Ñ–∏—á–µ—Å–∫–∏—Ö –¥–∞–Ω–Ω—ã—Ö. –ë–æ–ª—å—à–∞—è —á–∞—Å—Ç—å –º–æ–µ–≥–æ –≤–Ω–∏–º–∞–Ω–∏—è —Å–æ—Å—Ä–µ–¥–æ—Ç–æ—á–µ–Ω–∞ –Ω–∞ –ø–µ—Ä–µ—Å–µ—á–µ–Ω–∏–∏ –∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–æ–π —Ö–∏–º–∏–∏ –∏ —Ç–µ–æ—Ä–µ—Ç–∏–∫–æ-–≥—Ä–∞—Ñ–æ–≤–æ–π –æ–±—Ä–∞–±–æ—Ç–∫–∏ –¥–∞–Ω–Ω—ã—Ö. –í –Ω–∞—Å—Ç–æ—è—â–µ–µ –≤—Ä–µ–º—è –ø–æ–≥—Ä—É–∂–∞—é—Å—å –≤ –º–∏—Ä –ø—Ä–µ–¥–ø—Ä–∏–Ω–∏–º–∞—Ç–µ–ª—å—Å—Ç–≤–∞.  

    
      
    
  

–Ø –ø–æ–ª—É—á–∏–ª –¥–æ–∫—Ç–æ—Ä—Å–∫—É—é —Å—Ç–µ–ø–µ–Ω—å. üéì –ø–æ —ç–∫—Å–ø–µ—Ä–∏–º–µ–Ω—Ç–∞–ª—å–Ω–æ–π —Ñ–∏–∑–∏–∫–µ –≤ –ë–µ—Ä–Ω—Å–∫–æ–º —É–Ω–∏–≤–µ—Ä—Å–∏—Ç–µ—Ç–µ –ø–æ–¥ —Ä—É–∫–æ–≤–æ–¥—Å—Ç–≤–æ–º –ø—Ä–æ—Ñ–µ—Å—Å–æ—Ä–∞ –ü–∏—Ç–µ—Ä–∞ –í—É—Ä—Ü–∞ –∏ –¥–æ–∫—Ç–æ—Ä–∞ –ú–µ–π–∫–µ—Ä–∞ –¢—É–ª–µ—è. –ë—É–∫–≤–∞ –ê –≤ –º–æ–µ–º –∏–º–µ–Ω–∏ –æ–∑–Ω–∞—á–∞–µ—Ç –º–æ–µ –æ—Ç—á–µ—Å—Ç–≤–æ –∏ —á–∏—Ç–∞–µ—Ç—Å—è –∫–∞–∫ –ê–±—É–±–∞–∫–∏—Ä–æ–≤–∏—á (–ê–±—É–±–∞–∫–∏—Ä–æ–≤–∏—á). –ó–Ω–∞—á–∏—Ç–µ–ª—å–Ω–∞—è —á–∞—Å—Ç—å –º–æ–∏—Ö –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–π —Å–≤—è–∑–∞–Ω–∞ —Å —Å–æ–∑–¥–∞–Ω–∏–µ–º —Å—Ç—Ä—É–∫—Ç—É—Ä–∏—Ä–æ–≤–∞–Ω–Ω—ã—Ö –≤ –≤–∏–¥–µ –≥—Ä–∞—Ñ–æ–≤ –æ–±—ä–µ–∫—Ç–æ–≤ –∏–∑ —Ö–∏–º–∏—á–µ—Å–∫–∏—Ö –¥–∞–Ω–Ω—ã—Ö/—Å–µ–Ω—Å–æ—Ä–Ω—ã—Ö –¥–∞–Ω–Ω—ã—Ö –∏ —ç—Ñ—Ñ–µ–∫—Ç–∏–≤–Ω—ã–º –∏–∑—É—á–µ–Ω–∏–µ–º —Å—Ç—Ä—É–∫—Ç—É—Ä–Ω–æ–π –æ—Ä–≥–∞–Ω–∏–∑–∞—Ü–∏–∏ —Ç–∞–∫–∏—Ö –æ–±—ä–µ–∫—Ç–æ–≤. –í –±–æ–ª–µ–µ —à–∏—Ä–æ–∫–æ–º —Å–º—ã—Å–ª–µ –º–æ–µ –∏—Å—Å–ª–µ–¥–æ–≤–∞–Ω–∏–µ –±—ã–ª–æ –ø–æ—Å–≤—è—â–µ–Ω–æ –æ–±—ä–µ–¥–∏–Ω–µ–Ω–∏—é —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏ –∞–ø–ø–∞—Ä–∞—Ç–Ω–æ–≥–æ –∏ –ø—Ä–æ–≥—Ä–∞–º–º–Ω–æ–≥–æ –æ–±–µ—Å–ø–µ—á–µ–Ω–∏—è –¥–ª—è —ç—Ñ—Ñ–µ–∫—Ç–∏–≤–Ω–æ–≥–æ –∏ –±—ã—Å—Ç—Ä–æ–≥–æ –∏–∑–≤–ª–µ—á–µ–Ω–∏—è –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏–∏ –∏–∑ –∞–Ω–∞–ª–∏—Ç–∏—á–µ—Å–∫–∏—Ö —É—Å—Ç–∞–Ω–æ–≤–æ–∫. –Ø –ø–æ–ª—É—á–∏–ª —Å—Ç–µ–ø–µ–Ω—å –º–∞–≥–∏—Å—Ç—Ä–∞ –∏ –±–∞–∫–∞–ª–∞–≤—Ä–∞ –≤ –æ–±–ª–∞—Å—Ç–∏ –≥–µ–æ—Ñ–∏–∑–∏–∫–∏ –≤ –°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥—Å–∫–æ–º –≥–æ—Å—É–¥–∞—Ä—Å—Ç–≤–µ–Ω–Ω–æ–º —É–Ω–∏–≤–µ—Ä—Å–∏—Ç–µ—Ç–µ –≤ –°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥–µ, –†–æ—Å—Å–∏—è.



–ü—É–±–ª–∏–∫–∞—Ü–∏–∏ —Å–º. –≤ Google Scholar –∏–ª–∏ –≤ –º–æ–µ–º –ø—Ä–æ—Ñ–∏–ª–µ LOOP. –ö–æ–¥ —Å–º. –Ω–∞ GitHub. –ù–µ —Å—Ç–µ—Å–Ω—è–π—Ç–µ—Å—å —Å–≤—è–∑–∞—Ç—å—Å—è —Å–æ –º–Ω–æ–π –ø–æ —Å—Å—ã–ª–∫–∞–º, –ø—Ä–∏–∫—Ä–µ–ø–ª–µ–Ω–Ω—ã–º –Ω–∏–∂–µ.

      
      > - [**Curriculum Vitae** üëî](/cv/)  
        
      > - [**Publications** üìù](/publications/)  

      > - [**Contact me** üìß](/contact/)
  
        
      
      You can also follow me on social media:
        
      > - [**Instagram** üì∑](https://www.instagram.com/lukmanovr/)/[**Twitter** üê¶](/archives/) / [**LinkedIn** üßë‚Äçüíº](https://www.linkedin.com/in/rustam-lukmanov-604695100/) / [**Telegram** ‚òéÔ∏è](https://t.me/lukmanovr)
        

      Sometimes, I write here about random things, check it out below:  
      
      > - [**Archive** üóÉÔ∏è](/archives/)
"
  en:
    params:
          title: Rustam A. Lukmanov
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true #Swithces on JS scritps and tags


enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rustam A. Lukmanov
  description: "Personal website"
  keywords: [Blog, Portfolio, PaperMod]
  paginate: 100
  #author: Lukmanov R.A.
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  ##Search paprams
  params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/circle3.png"
    favicon16x16: "/circle3.png"
    favicon32x32: "/circle3.png"
    apple_touch_icon: "/circle3.png"
    safari_pinned_tab: "/circle3.png"

  label:
    text: "| R.A. Lukmanov "
    icon: /circle.png
    iconHeight: 35

  # profile-mode
 # profileMode:
    enabled: true # needs to be explicitly set
    title: Hi \U0001f44b there!
    #subtitle: "This is subtitle"
    subtitle: "
    


> ### Hi \U0001f44b I am a Research Scientist. I am interested in scalable, principled methods for analyzing graph data in an unsupervised manner. &nbsp;  


I received Ph.D. \U0001f393 in experimental phyiscs at the University of Bern, advised by Prof. Peter Wurz. I did my masters and bachelors at Saint Petersburg State University in Saint Petersburg, Russia. My M.Sc. advisor was Alexey Goncharov. In Russian, my name reads as –†—É—Å—Ç–∞–º –õ—É–∫–º–∞–Ω–æ–≤.

For publications, see Google Scholar. For code, see GitHub.

Feel free to contact me by email: mail at rustam-lukmanov dot ru.


> Right now I am working on "
    #imageUrl: "/box.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: my image
    buttons:
      - name: Blog
        url: blog
      - name: Publications
        url: publications
      - name: Resume
        url: cv
      - name: Contact Information
        url: contact
  # home-info mode
  homeInfoParams:
    Title: " [Rustam A. Lukmanov üë®üèª‚Äçüî¨](/cv/)"
    Content: " 
    <p> I am a Research Scientist interested in scalable, unsupervised methods for construction and analysis of graph data. Most of my focus lies in the intersection of analytical chemsitry and graph-theoretic data processing. Currently, dabbling in the world of entrepreneurship
    </p>
    <br/>
    <p>   


    </p>  

  
  
      I received a Ph.D. \U0001f393 in experimental phyiscs at the [<u>University of Bern</u>](https://www.unibe.ch/index_eng.html), advised by [<u>Prof. Peter Wurz</u>](https://www.space.unibe.ch/about_us/personen/prof_dr_wurz_peter/index_eng.html) and [<u>Dr. Maker Tulej</u>](http://www.marek-tulej.ch/). 
        
      The A. in my name stands for my patronym and it reads as Abubakirovich (–ê–±—É–±–∞–∫–∏—Ä–æ–≤–∏—á).
        
        Considerable part of my research is about creating graph-structured objects from chemical/sensor data and efficient mining of the structural organization of such objects. More broadly my reaserch devoted to bridging the hardware and software development for **efficient** and **fast** insight retrieval from analytical setups.  I did my master's and bachelor's in Geophysics at [<u>Saint Petersburg State University</u>](https://english.spbu.ru/) in Saint Petersburg, Russia.  
   <p>
   <br/>
   </p>   
               

      For publications, see [**Google Scholar**](https://scholar.google.ch/citations?user=uJXEpcgAAAAJ&hl=en&oi=ao) or my [**LOOP**](https://loop.frontiersin.org/people/1234341/overview) profile. For code, see GitHub.

      Feel free to contact me through links attached below.

      
      > - [**Curriculum Vitae** üëî](/cv/)  
        
      > - [**Publications** üìù](/publications/)  

      > - [**Contact me** üìß](/contact/)
  
        
      
      You can also follow me on social media:
        
      > - [**Instagram** üì∑](https://www.instagram.com/lukmanovr/)/[**Twitter** üê¶](/archives/) / [**LinkedIn** üßë‚Äçüíº](https://www.linkedin.com/in/rustam-lukmanov-604695100/) / [**Telegram** ‚òéÔ∏è](https://t.me/lukmanovr)
        

      Sometimes, I write here about random things, check it out below:  
      
      > - [**Archive** üóÉÔ∏è](/archives/)"
  #socialIcons:
  #  - name: twitter
  #    url: "https://twitter.com/"
  #  - name: stackoverflow
  #    url: "https://stackoverflow.com"
  #  - name: github
  #    url: "https://github.com/"
  #  - name: google scholar
  #    url: "https://scholar.google.ch/citations?user=uJXEpcgAAAAJ&hl=en&oi=ao/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Publications
      name: Publications
      url: /publications/
      weight: 30
    - identifier: CV
      name: CV
      url: /CV/
      weight: 40
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: Search
      name: Search
      url: /search/
      weight: 60